version: '3.8'

services:
  flask_wog:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE}
    container_name: wog_flask_container
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    environment:
      - FLASK_PORT=${FLASK_PORT}
    volumes:
      - ./Scores.txt:/wog/Scores.txt
      - ./tests/e2e.py:/wog/tests/e2e.py
    command: ["sh", "-c", "flask --app main_score.py run --host=0.0.0.0 --port=${FLASK_PORT}"]
